# Generated by Django 5.2.4 on 2025-09-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название тега')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Стог тега')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
