# Generated by Django 5.2.4 on 2025-09-20 07:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0001_initial'),
        ('posts', '0002_alter_post_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collectionitems',
            unique_together={('user', 'post', 'collection')},
        ),
    ]
